# NNI experiment configuration (see https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html)
# This file is used by DeepCV as an experiment configuration template for all hyperparameter searches using [Neural Network Intelligence](https://nni.readthedocs.io)
# NOTE: These configurations are common to all hyperparameter searches, if you need to configure an hyperparameter search for a specific model, you should modify appropriate hp search configuration in parameters.yml
authorName: "" # Will be populated automatically by DeepCV (named after current git username, which is the same as mlflow user)
experimentName: "" # Will be populated automatically by DeepCV (named after mlflow experiment name)
searchSpacePath: "./hp_search_spaces/object_detector_hp_search_space.json" # Will be determined by model name to be "./conf/base/hp_search_spaces/<model_name>_search_space.json" or will be overriden by your hp search configuration in parameters.yml ('searchSpacePath' entry if any)
trialConcurrency: 1 # Will be populated automatically by DeepCV according to distributed configuration and/or number of available GPUs
maxTrialNum: -1 # Can be overriden by trials number ('maxTrialNum') you configured for your hyperparameter search in parameters.yml
# maxExecDuration: 2h # Feel free to uncomment this if you want a default maximal execution duration for all of your hyperparameter searches. Can be overriden by your hyperparameter search config in parameters.yml
trainingServicePlatform: local # choices: "local", "remote", "pai", "kubeflow"
useAnnotation: false
tuner:
  builtinTunerName: TPE # choices: "TPE", "Random", "Anneal", "Evolution"
  classArgs:
    optimize_mode: minimize # choices: "maximize", "minimize"
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: minimize
    start_step: 5
trial:
  command: kedro run --pipeline=... # Determined by DeepCV when performing an HP search over a given pipeline
  codeDir: ../../src/deepcv # Filled automatically by DeepCV to deepcv module source directory
  gpuNum: 0
